// Package art_api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package art_api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "OpenShift Team ART",
            "url": "https://example.com/",
            "email": "aos-team-art@redhat.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/releases/{name}": {
            "get": {
                "description": "Get the info of specified release",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Get release info",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Release name",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Release"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Assembly": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                }
            }
        },
        "main.Release": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "boolean"
                },
                "assembly": {
                    "$ref": "#/definitions/main.Assembly"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Example ART API Server",
	Description:      "This is a sample ART API server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
